name: Apply generated configuration to local Kong gateway and update API documentation

on:
  push:
    branches:
      - master

jobs:
  deploy_to_kong:
    runs-on: self-hosted
    name: Apply generated configuration to local Kong gateway and update API documentation
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Kong declarative configuration from Spec
        run: inso generate config ./openapi/orders.yaml --type declarative > kong2.x.yaml
      - name: Convert configuration for 3.0
        run: deck convert --from kong-gateway-2.x --to kong-gateway-3.x --input-file kong2.x.yaml --output-file kong3-b.x.yaml
      - name: fix temporary regex issue 
        run: sed 's/\\//' kong3-b.x.yaml > kong3.x.yaml
      - name: Validate Kong declarative configuration
        run: deck validate -s kong3.x.yaml
      - name: Deploy declarative config
        run: deck sync -s kong3.x.yaml
      - name: Publish Spec to Dev Portal
        run: cd ./openapi && http --check-status --ignore-stdin PUT :8001/default/files/specs/orders.yaml contents=@orders.yaml
